# Generated by Django 3.1.2 on 2020-12-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20201205_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
